// Cannabis Blog articles. Body blocks: ['h2', text] ['p', text] ['ul', [items]].
// Written as general education — no medical claims; readers are pointed to their doctor.

const DISCLAIMER =
  'This article is for general information only and is not medical advice. Hemp-derived products are for adults 21+. Talk to your doctor before using cannabinoids, especially if you take medication, are pregnant or nursing.'

export const ARTICLES = [
  {
    slug: 'what-is-the-difference-between-thc-vs-thca',
    title: 'What Is the Difference Between THC and THCa?',
    date: '2026-02-18',
    image: '/assets/images/2026/02/1-THCVSTHCA.webp',
    tags: ['thca', 'delta-9-thc'],
    excerpt: 'THCa and THC are closely related, but they are not the same thing. Here’s how heat turns one into the other — and why it matters when you shop.',
    body: [
      ['p', 'If you have browsed our THCa flower, you may have wondered how it differs from THC. The short answer: THCa is the form of THC that the hemp plant actually produces. Heat turns it into THC.'],
      ['h2', 'THCa: the raw form'],
      ['p', 'Living and freshly harvested cannabis plants make tetrahydrocannabinolic acid — THCa. In this raw form it has an extra “acid” group attached to the molecule, and it is not considered intoxicating on its own.'],
      ['h2', 'How THCa becomes THC'],
      ['p', 'When THCa is heated, that acid group breaks off. The process is called decarboxylation, and it happens quickly when flower is smoked, vaped or dabbed. The result is Delta 9 THC.'],
      ['ul', ['Smoking or vaping THCa flower: converts almost immediately.', 'Dabbing THCa concentrates: converts at the high temperatures used.', 'Eating raw THCa flower: little to no conversion, so the experience is very different.']],
      ['h2', 'Why it matters when you shop'],
      ['p', 'Because heat converts THCa into THC, heated THCa products can feel much like traditional cannabis. Look at the “Total THC” figure on a lab report to understand the potency you will actually get after heating.'],
      ['p', 'Laws on THCa differ between states, so check what applies where you live before ordering.'],
    ],
  },
  {
    slug: 'benefits-of-vaping-thca-carts',
    title: 'Why People Choose THCa Carts',
    date: '2026-02-14',
    image: '/assets/images/2026/02/2-BenefitsOfVapingTHCCarts.webp',
    tags: ['thca', 'vapes'],
    excerpt: 'Convenient, discreet and full of flavour — a look at why THCa vape cartridges are so popular, and how to use them well.',
    body: [
      ['p', 'THCa vape cartridges have become one of the most popular ways to enjoy THCa. Here is what draws people to them, and a few tips for getting the best experience.'],
      ['h2', 'What makes carts popular'],
      ['ul', ['Convenience: no grinding, rolling or cleaning up.', 'Discretion: vapour is less noticeable than smoke and fades quickly.', 'Consistency: each puff delivers a similar amount, so it is easier to pace yourself.', 'Flavour: many carts use strain-specific terpenes for a true-to-strain taste.']],
      ['h2', 'Getting the most from your cart'],
      ['ul', ['Use a 510-thread battery at a low-to-medium voltage — too much heat can burn the oil and dull the flavour.', 'Take short, gentle draws and wait a few minutes before taking more.', 'Store carts upright at room temperature, away from direct sunlight.']],
      ['h2', 'Choosing a quality cartridge'],
      ['p', 'Look for products with a current certificate of analysis (COA) from a third-party lab. It confirms cannabinoid content and screens for residual solvents and heavy metals.'],
    ],
  },
  {
    slug: 'best-ways-to-smoke-thca-diamonds',
    title: 'The Best Ways to Enjoy THCa Diamonds',
    date: '2026-02-10',
    image: '/assets/images/2026/02/3-BestWayToSmokeTHCaDiamonds.webp',
    tags: ['thca', 'concentrates'],
    excerpt: 'THCa diamonds are among the purest hemp concentrates available. Here are the most common ways to use them — from dab rigs to topping a bowl.',
    body: [
      ['p', 'THCa diamonds are crystalline concentrates that can be over 90% THCa. They are potent, so a little goes a long way. These are the most common ways people enjoy them.'],
      ['h2', '1. Dab rig or e-rig'],
      ['p', 'The classic method. Heat a quartz banger (or use an electronic rig), let it cool slightly, then add a small diamond. Lower temperatures preserve more flavour.'],
      ['h2', '2. Concentrate vaporiser'],
      ['p', 'Portable dab pens and concentrate vapes offer precise temperature control without a torch — a convenient option for beginners.'],
      ['h2', '3. Topping a bowl or joint'],
      ['p', 'Crush a small diamond and sprinkle it over flower to add potency. Start with a very small amount; the effect is much stronger than flower alone.'],
      ['h2', 'A note on dosing'],
      ['p', 'Diamonds are far more concentrated than flower. Begin with a piece smaller than a grain of rice and wait before having more.'],
    ],
  },
  {
    slug: 'how-long-do-delta-9-gummies-last',
    title: 'How Long Do Delta 9 Gummies Last?',
    date: '2026-02-06',
    image: '/assets/images/2026/02/2-HowLongDoesD9THCGummiesLast.webp',
    tags: ['delta-9-thc', 'gummies', 'edibles'],
    excerpt: 'From when they kick in to how long they stay fresh on the shelf — everything to know about the timing of Delta 9 gummies.',
    body: [
      ['p', '“How long do they last?” can mean two things: how long the effects last, and how long the gummies stay fresh. We cover both.'],
      ['h2', 'When do the effects start?'],
      ['p', 'Edibles are digested before they take effect, so they are slower than smoking or vaping. Most people feel something between 30 minutes and 2 hours after eating a gummy. Eating on an empty stomach can make it faster; a large meal can slow it down.'],
      ['h2', 'How long do the effects last?'],
      ['p', 'Effects from Delta 9 gummies commonly last 4 to 8 hours, with the strongest period a few hours in. Dose, metabolism and tolerance all play a part.'],
      ['h2', 'The golden rule: wait before taking more'],
      ['p', 'The most common mistake is taking a second gummy because the first “isn’t working”. Give it at least two hours before deciding to have more.'],
      ['h2', 'How long do gummies stay fresh?'],
      ['ul', ['Unopened, most gummies keep for 6–12 months — check the date on the package.', 'Store them in a cool, dry place in the original container.', 'Heat and humidity make gummies stick together and can reduce potency over time.']],
    ],
  },
  {
    slug: 'potential-health-benefits-of-delta-8-delta-9-and-delta-10',
    title: 'Delta 8, Delta 9 and Delta 10: What’s the Difference?',
    date: '2026-02-02',
    image: '/assets/images/2026/02/3-TipsForFlyingWithD9.webp',
    tags: ['delta-8-thc', 'delta-9-thc', 'delta-10-thc'],
    excerpt: 'Three forms of THC, three different experiences. A plain-English comparison to help you choose.',
    body: [
      ['p', 'Delta 8, Delta 9 and Delta 10 THC share almost the same chemical structure — the number refers to where one particular bond sits in the molecule. That small difference changes how people describe the experience.'],
      ['h2', 'Delta 9 THC'],
      ['p', 'The best-known form of THC and the main active compound in cannabis. Hemp-derived Delta 9 products are usually edibles or drinks with precise, measured doses.'],
      ['h2', 'Delta 8 THC'],
      ['p', 'Often described as milder and more clear-headed than Delta 9. It is a common choice for people who want a gentler experience.'],
      ['h2', 'Delta 10 THC'],
      ['p', 'Usually described as the lightest of the three, with a more upbeat, daytime feel.'],
      ['h2', 'Which one is right for you?'],
      ['p', 'Everyone responds differently. If you are unsure, start with a low dose of one type, note how you feel, and adjust from there. Our team is happy to help you choose — just message us.'],
      ['p', 'Research into these cannabinoids is still developing, and none of these products are intended to diagnose, treat, cure or prevent any disease.'],
    ],
  },
  {
    slug: 'delta-9-edibles-the-future-of-wellness',
    title: 'Why Delta 9 Edibles Are So Popular',
    date: '2026-01-28',
    image: '/assets/images/2026/02/4-D9TheFutureOfWellness.webp',
    tags: ['delta-9-thc', 'edibles'],
    excerpt: 'Measured doses, no smoke and lots of choice. Why more adults are reaching for Delta 9 edibles.',
    body: [
      ['p', 'Hemp-derived Delta 9 edibles have grown quickly in popularity. Here are the main reasons adults choose them.'],
      ['ul', ['Precise dosing: every gummy or square contains a measured amount, which makes it easy to find what works for you.', 'Smoke-free: nothing to inhale.', 'Discreet: edibles look like everyday treats and have no lingering smell.', 'Longer-lasting: effects typically last longer than smoking or vaping.', 'Variety: gummies, chocolates, mints, drinks and more.']],
      ['h2', 'Tips for a good experience'],
      ['ul', ['Start with 2.5–5 mg if you are new to THC.', 'Wait at least two hours before taking more.', 'Keep edibles clearly labelled and out of reach of children and pets.']],
    ],
  },
  {
    slug: 'delta-9-vs-cbd-for-sleep-which-is-better',
    title: 'Delta 9 vs. CBD at Bedtime: How Do They Compare?',
    date: '2026-01-24',
    image: '/assets/images/2026/02/2-D9vsCBDForSleepWhichIsBetter.webp',
    tags: ['delta-9-thc', 'cbd', 'cbn', 'sleep'],
    excerpt: 'Many people add a cannabinoid to their evening routine. Here is how Delta 9, CBD and CBN blends differ.',
    body: [
      ['p', 'Evening blends are among our most popular products. They usually contain one or more of Delta 9 THC, CBD and CBN. Here is how they differ.'],
      ['h2', 'CBD'],
      ['p', 'Non-intoxicating, so it is a common choice for people who want to avoid feeling “high”. Many customers use CBD as part of a calm evening routine.'],
      ['h2', 'Delta 9 THC'],
      ['p', 'Intoxicating. Low doses of Delta 9 are often included in night-time gummies. Effects vary more from person to person than with CBD.'],
      ['h2', 'CBN and blends'],
      ['p', 'CBN is frequently combined with CBD or Delta 9 in products designed for the evening. Blends let you get a bit of each.'],
      ['h2', 'Good sleep habits still matter most'],
      ['p', 'A consistent bedtime, a dark cool room and less screen time before bed make the biggest difference. If you have ongoing trouble sleeping, speak to a doctor.'],
    ],
  },
  {
    slug: 'guide-to-delta-8-delta-9-and-cbd-for-better-sleep',
    title: 'A Guide to Night-Time Cannabinoid Products',
    date: '2026-01-20',
    image: '/assets/images/2026/02/1SLEEP.webp',
    tags: ['sleep', 'cbd', 'cbn', 'delta-8-thc', 'delta-9-thc'],
    excerpt: 'How to choose and use night-time gummies, tinctures and blends — and what to look for on the label.',
    body: [
      ['p', 'If you are considering a cannabinoid product for your evening routine, these tips will help you choose.'],
      ['h2', 'Read the label'],
      ['ul', ['Cannabinoids and amounts per serving (for example “5 mg Delta 9 + 25 mg CBN”).', 'Total servings per package.', 'A QR code or batch number that links to a lab report.']],
      ['h2', 'Timing'],
      ['p', 'Edibles take 30 minutes to 2 hours to work, so many people take them an hour or so before bed. Tinctures held under the tongue can act a little faster.'],
      ['h2', 'Start low'],
      ['p', 'Begin with the smallest suggested serving and keep a simple note of how you feel the next morning. Adjust gradually.'],
      ['h2', 'Browse our night-time picks'],
      ['p', 'See products customers choose for the evening on our Shop by Effect → Sleep page.'],
    ],
  },
  {
    slug: 'boost-creativity-with-delta-8-thc',
    title: 'Delta 8 and Creativity: What People Say',
    date: '2026-01-16',
    image: '/assets/images/2026/02/1ENERGY.webp',
    tags: ['delta-8-thc', 'energy-focus'],
    excerpt: 'Why some artists, musicians and makers enjoy Delta 8 — and how to keep it balanced.',
    body: [
      ['p', 'Some customers tell us they enjoy a small amount of Delta 8 THC during creative hobbies like music, drawing or writing. Because it is often described as milder than Delta 9, it appeals to people who want to stay clear-headed.'],
      ['h2', 'Keep it light'],
      ['ul', ['Try a low dose — you want to feel relaxed, not distracted.', 'Pair it with a clear goal for the session.', 'Stay hydrated and take breaks.']],
      ['h2', 'Know yourself'],
      ['p', 'Responses vary. If THC makes you anxious or unfocused, a non-intoxicating option such as CBG or CBD may suit you better. Never drive or operate machinery after using THC.'],
    ],
  },
  {
    slug: 'delta-8-delta-9-cbd-and-working-out',
    title: 'Cannabinoids and Your Workout Routine',
    date: '2026-01-12',
    image: '/assets/images/2026/02/2ENERGY.webp',
    tags: ['cbd', 'delta-8-thc', 'delta-9-thc', 'energy-focus', 'relief'],
    excerpt: 'Before, after, or not at all? Practical, safety-first guidance for active adults.',
    body: [
      ['p', 'Plenty of active adults include cannabinoids in their routine — most often CBD, and most often after a workout rather than before.'],
      ['h2', 'After exercise'],
      ['p', 'CBD topicals and gummies are popular as part of a wind-down routine after training, alongside stretching, hydration and good nutrition.'],
      ['h2', 'Before exercise'],
      ['p', 'THC can affect coordination and reaction time, so we do not recommend using THC before exercise, especially anything involving weights, heights, water or traffic.'],
      ['h2', 'Competitive athletes'],
      ['p', 'Many sports organisations test for THC. Even full-spectrum CBD contains trace THC. If you compete, choose THC-free products and check your organisation’s rules.'],
    ],
  },
  {
    slug: 'cbd-delta-8-and-delta-9-for-pain-management',
    title: 'CBD, Delta 8 and Delta 9: A Comfort-Focused Overview',
    date: '2026-01-08',
    image: '/assets/images/2026/02/3-CBDD8D9-for-pain-mgmt.webp',
    tags: ['cbd', 'delta-8-thc', 'delta-9-thc', 'relief', 'topicals'],
    excerpt: 'Topicals, tinctures and gummies — the product formats customers choose when they want to unwind, and what to consider.',
    body: [
      ['p', 'Customers often ask which products are best when they want to relax and feel more comfortable. We can’t give medical advice, but we can explain the options.'],
      ['h2', 'Topicals'],
      ['p', 'Creams, gels and balms are applied to the skin where you want them. They are a popular non-intoxicating option.'],
      ['h2', 'Tinctures and gummies'],
      ['p', 'Taken by mouth, these work throughout the body. CBD-only products are non-intoxicating; blends with Delta 8 or Delta 9 THC are intoxicating.'],
      ['h2', 'Talk to your doctor'],
      ['p', 'If you live with ongoing pain, speak with a healthcare professional before trying cannabinoids — CBD and THC can interact with some medications.'],
    ],
  },
  {
    slug: 'athletes-guide-to-cbd-and-delta-8-for-recovery',
    title: 'An Active Adult’s Guide to CBD and Delta 8',
    date: '2026-01-04',
    image: '/assets/images/2026/02/2RELIEF.webp',
    tags: ['cbd', 'delta-8-thc', 'relief'],
    excerpt: 'How active adults fit CBD and Delta 8 into rest days — plus what to know about drug testing.',
    body: [
      ['p', 'Rest and recovery are part of every good training plan. Some active adults add CBD, or occasionally Delta 8, to their rest-day routine.'],
      ['h2', 'Popular formats'],
      ['ul', ['CBD topicals after a long run or session.', 'CBD gummies or softgels as part of an evening routine.', 'Low-dose Delta 8 on rest days only — never before training or driving.']],
      ['h2', 'Drug testing'],
      ['p', 'Delta 8 and full-spectrum CBD can both cause a positive THC test. If you are tested, choose THC-free CBD and keep your receipts and lab reports.'],
    ],
  },
  {
    slug: 'pet-wellness-and-cbd',
    title: 'Pets and CBD: What Owners Should Know',
    date: '2025-12-30',
    image: '/assets/images/2026/02/1-PetWellnessAndCBD.webp',
    tags: ['cbd', 'cbd-for-dogs'],
    excerpt: 'Choosing a pet CBD product safely — including the one ingredient you should always avoid.',
    body: [
      ['p', 'CBD chews and oils made for pets are becoming common. If you are considering one, here is what to keep in mind.'],
      ['h2', 'Use products made for pets'],
      ['p', 'Pet products are dosed for smaller bodies and made with pet-safe ingredients. Never give your pet products made for people.'],
      ['h2', 'Avoid THC'],
      ['p', 'THC can be toxic to dogs and cats. Choose pet products that are THC-free or contain only trace amounts, and keep all THC products well out of reach.'],
      ['h2', 'Talk to your vet'],
      ['p', 'Check with your veterinarian before starting CBD, especially if your pet takes medication. Start with the lowest suggested serving and watch how your pet responds.'],
    ],
  },
].map((a) => ({ ...a, disclaimer: DISCLAIMER, readMinutes: Math.max(2, Math.round(a.body.flatMap((b) => (Array.isArray(b[1]) ? b[1] : [b[1]])).join(' ').split(/\s+/).length / 200)) }))

export const articleBySlug = Object.fromEntries(ARTICLES.map((a) => [a.slug, a]))

export function articlesForTags(tags, limit = 3) {
  if (!tags?.length) return ARTICLES.slice(0, limit)
  return ARTICLES.filter((a) => a.tags.some((t) => tags.includes(t))).slice(0, limit)
}
